version: "3.8"

services:
  wordpress:
    image: nexgear/empirelabs_wordpress_app
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      custom_net:
        ipv4_address: 10.11.0.2

  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_net:
        ipv4_address: 10.11.0.3

volumes:
  db_data: {}

networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/24
          gateway: 10.11.0.1
